# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/amazonlinux-2"

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.synced_folder '..', '/vagrant'
  config.vm.synced_folder '..', '/usr/local/xen-enforce-bot'

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
  end

  config.vm.provision :shell, inline: <<-SHELL
    set -xeuo pipefail
    yum install -y python python-pip
    pip install ansible~=2.10.3
    ansible-galaxy install -r /usr/local/xen-enforce-bot/Xen-Enforce-Bot/playbooks/requirements.yml
  SHELL

  config.vm.provision :ansible_local do |ansible|
      ansible.install = false
      ansible.playbook = 'Xen-Enforce-Bot/playbooks/vagrant.yml'

      prefixes = ['percona_', 'xen_']
      extra_vars = ENV.select do |k, v|
        prefixes.any? {|prefix| k.start_with? prefix}
      end
      extra_vars[:ansible_python_interpreter] = '/usr/bin/python2'
      extra_vars[:xen_is_vagrant] = true
      ansible.extra_vars = extra_vars

      ansible.verbose = ENV['vagrant_verbose'] || false
  end

end
