- hosts: all
  tasks:

    - name: Configure System Time
      include_role:
        name: timezone

    - name: Install Percona XtraDB Cluster
      include_role:
        name: percona-xtradb-cluster

    # TODO Configure Apache encryption.
    # TODO Configure database encryption
    # TODO Configure S3 Backups

    - name: Deploy Xen Enforce Bot
      include_role:
        name: xen-enforce-bot
