- hosts: all
  tasks:

    - name: Install Pip
      become: true
      ansible.builtin.yum:
        name: python-pip
        state: present

    - name: Configure System Time
      include_role:
        name: timezone

    - name: Install Percona XtraDB Cluster
      include_role:
        name: percona-xtradb-cluster

    - name: Configure S3 Backups
      include_role:
        name: percona-s3-backups

    - name: Deploy Xen Enforce Bot
      include_role:
        name: xen-enforce-bot

    - name: Configure HTTPS With Certbot
      include_role:
        name: certbot
