- hosts: all
  tasks:
    - name: Install Percona XtraDB Cluster
      include_role:
        name: percona-xtradb-cluster

    # TODO Set timezzone.
    # TODO Configure S3 Backups

    - name: Deploy Xen Enforce Bot
      include_role:
        name: xen-enforce-bot
