- hosts: all
  tasks:

    - name: Configure System Time
      include_role:
        name: timezone

    - name: Install Percona XtraDB Cluster
      include_role:
        name: percona-xtradb-cluster

    - name: Deploy Xen Enforce Bot
      include_role:
        name: xen-enforce-bot
